version: '3'
services:
  odoo:
    image: odoo:17
    user: root
    container_name: odooenterprise17
    ports:
      - "8015:8069"
    environment:
      - HOST=172.17.0.1
      - USER=odoo17
      - PASSWORD=odoo17
    volumes:
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo
    restart: always
    networks:
      - docker-pgadmin_default

networks:
  docker-pgadmin_default:
    external: true
